server:
  port: 7003
eureka:
  instance:
    appname: eureka-7003
  client:
    register-with-eureka: false #是否想注册中心注册自己
    fetch-registry: false # 值为false.则自己是注册中心
    serviceUrl:  # eureka服务段监视页面
#      defaultZone: http://localhost:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/